import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd]
src = Glob('board.c')
src += Glob('startup_gcc.s')
CPPPATH +=  [cwd + '/nxp_drivers']
CPPPATH +=  [cwd + '/drivers']

if GetDepend(['BSP_USING_GPIO']):
    src += Glob(cwd +'/drivers/gpio.c')

if GetDepend(['BSP_USING_GPIO_LED']):
    src += Glob(cwd +'/modules/led/led.c')
    CPPPATH +=  [cwd + '/modules/led']

if GetDepend(['BSP_USING_GPIO_KEY']):
    src += Glob(cwd +'/modules/key/key.c')
    CPPPATH +=  [cwd + '/modules/key']

if not GetDepend('RT_USING_NANO'):
    src += Glob(cwd + '/drivers/drv_uart.c')

objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
