import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd]
src = Glob('board.c')
src += Glob('startup_gcc.s')
CPPPATH +=  [cwd + '/nxp_drivers']

if GetDepend(['BSP_USING_GPIO']):
    src += Glob('gpio.c')
    src += Glob('led.c')

if not GetDepend('RT_USING_NANO'):
    src += Glob(cwd + 'drv_uart.c')

objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
