import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd]
src = Glob('board.c')
src += Glob('startup_gcc.s')
src += Glob(cwd +'/nxp_drivers/system_LPC11xx.c')
CPPPATH +=  [cwd + '/nxp_drivers']
CPPPATH +=  [cwd + '/drivers']

if GetDepend(['BSP_USING_GPIO']):
    src += Glob(cwd +'/drivers/gpio.c')

if GetDepend(['BSP_USING_IIC']):
    src += Glob(cwd +'/drivers/i2c.c')

if GetDepend(['BSP_USING_TIMER16']):
    src += Glob(cwd +'/drivers/timer16.c')

if GetDepend(['BSP_USING_TIMER32']):
    src += Glob(cwd +'/drivers/timer32.c')

if GetDepend(['BSP_USING_PID']):
    src += Glob(cwd +'/algorithm/pid/pid.c')
    CPPPATH +=  [cwd + '/algorithm/pid']

if GetDepend(['BSP_USING_GPIO_LED']):
    src += Glob(cwd +'/modules/led/led.c')
    CPPPATH +=  [cwd + '/modules/led']

if GetDepend(['BSP_USING_GPIO_KEY']):
    src += Glob(cwd +'/modules/key/key.c')
    CPPPATH +=  [cwd + '/modules/key']

if GetDepend(['BSP_USING_IIC_OLED']):
    src += Glob(cwd +'/modules/oled/oled.c')
    CPPPATH +=  [cwd + '/modules/oled']

if GetDepend(['BSP_USING_MOTOR']):
    src += Glob(cwd +'/modules/motor/motor.c')
    CPPPATH +=  [cwd + '/modules/motor']

if not GetDepend('RT_USING_NANO'):
    src += Glob(cwd + '/drivers/drv_uart.c')

objs = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
